"""Pre-compute a song's spectrum for the in-game audio visualizer.

    python tools/spectrum.py <song.mp3> <id> <out.js>

Needs numpy and soundfile (pip install numpy soundfile).

Browsers can't analyze audio live when the game is opened straight from its files (they treat local files as
cross-origin and hand back silence), so the visualizer plays back this file instead, in step with the song's clock.

Each frame holds BANDS values (0-255), one per frequency band, log-spaced from bass to treble like cava's bars.
Every band is scaled to its own loud moments, so treble bars move as much as the bass ones.
"""

import base64
import json
import sys

import numpy as np
import soundfile as sf

FPS = 30
BANDS = 48
LOW_HZ, HIGH_HZ = 40, 12000
N_FFT = 4096


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    song_path, song_id, out_path = sys.argv[1:]
    audio, sr = sf.read(song_path)
    x = audio.mean(axis=1) if audio.ndim > 1 else audio

    hop = sr / FPS
    frames = int(len(x) / hop)
    window = np.hanning(N_FFT)
    padded = np.concatenate([np.zeros(N_FFT // 2), x, np.zeros(N_FFT)])
    freqs = np.fft.rfftfreq(N_FFT, 1 / sr)
    edges = np.geomspace(LOW_HZ, HIGH_HZ, BANDS + 1)
    bins = [np.where((freqs >= lo) & (freqs < max(hi, lo + sr / N_FFT)))[0] for lo, hi in zip(edges[:-1], edges[1:])]
    # bands narrower than one FFT bin borrow the nearest bin
    bins = [b if len(b) else np.array([np.argmin(np.abs(freqs - lo))]) for b, lo in zip(bins, edges[:-1])]

    level = np.zeros((frames, BANDS))
    for f in range(frames):
        start = int(f * hop)
        mag = np.abs(np.fft.rfft(padded[start:start + N_FFT] * window))
        level[f] = [mag[b].mean() for b in bins]

    # decibels, then each band scaled between its quiet floor and its loud peaks
    db = 20 * np.log10(level + 1e-9)
    lo = np.percentile(db, 30, axis=0)
    hi = np.percentile(db, 99, axis=0)
    norm = np.clip((db - lo) / np.maximum(hi - lo, 1e-6), 0, 1) ** 1.3
    data = (norm * 255).round().astype(np.uint8)

    payload = {'fps': FPS, 'bands': BANDS, 'frames': frames, 'data': base64.b64encode(data.tobytes()).decode()}
    with open(out_path, 'w', newline='\n') as f:
        f.write(f'// Generated by tools/spectrum.py from {song_path}: {BANDS} bands x {frames} frames at {FPS} fps.\n')
        f.write('window.SPECTRA = window.SPECTRA || {};\n')
        f.write(f'window.SPECTRA[{json.dumps(song_id)}] = {json.dumps(payload)};\n')
    print(f'{frames} frames x {BANDS} bands -> {out_path}')


if __name__ == '__main__':
    main()
